-- MySQL Script generated by MySQL Workbench
-- gio 3 set 2020, 17:21:21
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ecommerce` ;

-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecommerce` ;
-- -----------------------------------------------------
-- Schema users
-- -----------------------------------------------------
USE `ecommerce` ;

-- -----------------------------------------------------
-- Table `ecommerce`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`role` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`role` (
  `roleName` VARCHAR(40) NOT NULL DEFAULT 'Cliente',
  PRIMARY KEY (`roleName`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

-- -----------------------------------------------------
-- Table `ecommerce`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`user` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`user` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(128) NOT NULL,
  `role` VARCHAR(40) NOT NULL DEFAULT 'Cliente',
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `ecommerce`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`orders` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`orders` (
  `numOrder` INT(11) NOT NULL AUTO_INCREMENT,
  `idUser` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `status` ENUM('In preparazione', 'Spedito', 'Consegnato') NOT NULL DEFAULT 'In preparazione',
  PRIMARY KEY (`numOrder`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `ecommerce`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`category` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`category` (
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(200) NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

-- -----------------------------------------------------
-- Table `ecommerce`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`product` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`product` (
  `code` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `description` VARCHAR(100) NULL DEFAULT NULL,
  `price` INT(11) NULL DEFAULT 0,
  `quantity` INT(11) NULL DEFAULT 0,
  `photo` MEDIUMBLOB NULL DEFAULT NULL,
  `iva` INT(3) NOT NULL DEFAULT 22,
  `category` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `ecommerce`.`purchase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`purchase` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`purchase` (
  `numorder` INT(11) NOT NULL,
  `code` INT(11) NOT NULL,
  `purchasedquantity` INT(4) NOT NULL DEFAULT 1,
  `price` INT(11) NOT NULL,
  `iva` INT(3) NOT NULL DEFAULT 22,
  `name` VARCHAR(20) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`numorder`, `code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `ecommerce`.`shipping`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`shipping` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`shipping` (
  `numOrder` INT(11) NOT NULL,
  `company` VARCHAR(255) NOT NULL,
  `trackingNum` VARCHAR(45) NULL,
  PRIMARY KEY (`numOrder`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

-- -----------------------------------------------------
-- Table `ecommerce`.`user_anagraphics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`user_anagraphics` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`user_anagraphics` (
  `idUser` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `phonenumber` VARCHAR(13) NOT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `ecommerce`.`billing`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`billing` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`billing` (
  `idBill` INT NOT NULL AUTO_INCREMENT,
  `numOrder` INT(11) NOT NULL,
  `address` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  `codfiscale` VARCHAR(45) NULL,
  PRIMARY KEY (`idBill`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `ecommerce`.`gallery`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`gallery` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`gallery` (
  `idPhoto` INT(4) NOT NULL AUTO_INCREMENT,
  `codeProduct` INT(11) NOT NULL,
  `picture` BLOB NOT NULL,
  PRIMARY KEY (`idPhoto`, `codeProduct`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
